name: $(Date:yyyyMMdd).$(Rev:r)
pr: 
- 'master'
jobs:
- template: Extension/jobs/build.mac.yml
  parameters:
    name: macOS
    pool:
      vmImage: 'macOS-10.14'

- template: Extension/jobs/build.linux.yml
  parameters:
    name: Linux
    pool:
      vmImage: 'ubuntu-20.04'

- template: Extension/jobs/build.windows.yml